### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by JaniceLC** [xiaoxuegao499/LA-DNN-for-COVID-19-diagnosis#2]
Hi Xiaoxue @xiaoxuegao499, 

I am wondering which version of pytorch you are using for this repository? 

Thank you for your help.

**Comment by xiaoxuegao499** [comment]
> Hi Xiaoxue @xiaoxuegao499,
> 
> I am wondering which version of pytorch you are using for this repository?
> 
> Thank you for your help.

Dear JaniceLC,
We are glad that you are interested in our project!
The version of PyTorch we use is 1.5.0.
