### ISSUE TITLE
Unable to extract the splitted tars to obtain the model

### ISSUE THREAD

**Issue by ytxmobile98** [xiaoxuegao499/LA-DNN-for-COVID-19-diagnosis#3]
I have stepped into the best_model directory. However, when I try to extract the tars by typing
```
$ cat densenet169.path.tar.0* | tar -x
```
It produces the following error messages:
```
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

**Comment by xiaoxuegao499** [comment]
You can try to merge these 8 splitted tars first. 
If it is still unavailable, please download the pre-trained model from [Baidu Netdisk](https://pan.baidu.com/s/1fnvSEnjRGXh--KY9IY3NpA)(extract code w3i1).

**Comment by ytxmobile98** [comment]
> You can try to merge these 8 splitted tars first.
> If it is still unavailable, please download the pre-trained model from [Baidu Netdisk](https://pan.baidu.com/s/1fnvSEnjRGXh--KY9IY3NpA)(extract code w3i1).

Thanks~~

**Comment by ytxmobile98** [comment]
> You can try to merge these 8 splitted tars first.
> If it is still unavailable, please download the pre-trained model from [Baidu Netdisk](https://pan.baidu.com/s/1fnvSEnjRGXh--KY9IY3NpA)(extract code w3i1).

But what do you mean by **merging** the 8 tar files?
I attempted to use the `cat` command on Ubuntu to generate the tar file and extract it, without any positive outcomes.
